version: "3.1"

services:
  demo_app:
    container_name: demo_app
    image: cyanskyyy/demo_app:latest
    build: .
    ports:
      - 8081:8080
    environment:
      - DATABASE_URL=jdbc:postgresql://demo_db:5435/springbootdemodb
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=password
    depends_on:
      - demo_db

  demo_db:
    container_name: demo_db
    image: postgres:16-bullseye
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: springbootdemodb
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
